/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

DWORD __cdecl sub_401000(LPCSTR lpExistingFileName, char a2);
DWORD __cdecl sub_4010F0(LPCSTR lpFileName);
HANDLE sub_401230();
int __cdecl sub_4013E0(int a1, int a2);
int __stdcall WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd);
int sub_4017B0();
// HANDLE __stdcall CreateFileA(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
// BOOL __stdcall WriteFile(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped);
// DWORD __stdcall SetFilePointer(HANDLE hFile, LONG lDistanceToMove, PLONG lpDistanceToMoveHigh, DWORD dwMoveMethod);
// DWORD __stdcall GetLastError();
// void __stdcall Sleep(DWORD dwMilliseconds);
// DWORD __stdcall GetFileAttributesA(LPCSTR lpFileName);
// int __stdcall lstrlenA(LPCSTR lpString);
// BOOL __stdcall DeleteFileA(LPCSTR lpFileName);
// BOOL __stdcall RemoveDirectoryA(LPCSTR lpPathName);
// BOOL __stdcall GetFileSizeEx(HANDLE hFile, PLARGE_INTEGER lpFileSize);
// BOOL __stdcall FlushFileBuffers(HANDLE hFile);
// BOOL __stdcall CreateProcessA(LPCSTR lpApplicationName, LPSTR lpCommandLine, LPSECURITY_ATTRIBUTES lpProcessAttributes, LPSECURITY_ATTRIBUTES lpThreadAttributes, BOOL bInheritHandles, DWORD dwCreationFlags, LPVOID lpEnvironment, LPCSTR lpCurrentDirectory, LPSTARTUPINFOA lpStartupInfo, LPPROCESS_INFORMATION lpProcessInformation);
// LPSTR __stdcall lstrcatA(LPSTR lpString1, LPCSTR lpString2);
// DWORD __stdcall GetTempPathA(DWORD nBufferLength, LPSTR lpBuffer);
// DWORD __stdcall GetModuleFileNameA(HMODULE hModule, LPSTR lpFilename, DWORD nSize);
// BOOL __stdcall CloseHandle(HANDLE hObject);
// BOOL __stdcall MoveFileA(LPCSTR lpExistingFileName, LPCSTR lpNewFileName);
// int sprintf(char *Dest, const char *Format, ...);
// char *__cdecl strrchr(const char *Str, int Ch);
// int __cdecl rand();
// int _p___argc(void); weak
// int _p___argv(void); weak

//-------------------------------------------------------------------------
// Data declarations

char Format[] = ":L1\r\nDEL \"%s\"\r\nPING 0.0.0.0 > nul\r\nIF EXIST \"%s\" GOTO L1\r\nDEL \"%%0\"\r\n"; // idb


//----- (00401000) --------------------------------------------------------
DWORD __cdecl sub_401000(LPCSTR lpExistingFileName, char a2)
{
  const CHAR *v2; // ebx
  char *v3; // eax
  char *v4; // esi
  char v5; // al
  char Str; // [esp+Ch] [ebp-104h]
  char v8; // [esp+Dh] [ebp-103h]
  __int16 v9; // [esp+10Dh] [ebp-3h]
  char v10; // [esp+10Fh] [ebp-1h]

  Str = 0;
  v2 = lpExistingFileName;
  memset(&v8, 0, 0x100u);
  v9 = 0;
  v10 = 0;
  strcpy(&Str, lpExistingFileName);
  v3 = strrchr(&Str, 92);
  if ( v3 )
    v4 = v3 + 1;
  else
    v4 = &Str;
  if ( *v4 )
  {
    do
    {
      *v4 = rand() % 26 + 97;
      v5 = (v4++)[1];
    }
    while ( v5 );
  }
  if ( MoveFileA(lpExistingFileName, &Str) )
    v2 = &Str;
  if ( a2 )
  {
    if ( !RemoveDirectoryA(v2) )
      return GetLastError();
  }
  else if ( !DeleteFileA(v2) )
  {
    return GetLastError();
  }
  return 0;
}

//----- (004010F0) --------------------------------------------------------
DWORD __cdecl sub_4010F0(LPCSTR lpFileName)
{
  HANDLE v1; // eax
  void *v2; // esi
  LONG v4; // eax
  DWORD v5; // ecx
  unsigned int v6; // ebp
  LONG v7; // edi
  unsigned __int8 v8; // of
  int v9; // eax
  DWORD v10; // ecx
  unsigned int v11; // kr00_4
  DWORD v12; // kr08_4
  LARGE_INTEGER FileSize; // [esp+Ch] [ebp-1014h]
  DWORD NumberOfBytesWritten; // [esp+14h] [ebp-100Ch]
  int v15; // [esp+1Ch] [ebp-1004h]
  char Buffer; // [esp+20h] [ebp-1000h]
  char v17; // [esp+21h] [ebp-FFFh]
  __int16 v18; // [esp+101Dh] [ebp-3h]
  char v19; // [esp+101Fh] [ebp-1h]

  Buffer = 0;
  memset(&v17, 0, 0xFFCu);
  v18 = 0;
  v19 = 0;
  v1 = CreateFileA(lpFileName, 0x40000000u, 0, 0, 3u, 0x80u, 0);
  v2 = v1;
  if ( v1 == (HANDLE)-1 )
    return GetLastError();
  SetFilePointer(v1, -1, 0, 2u);
  WriteFile(v2, &Buffer, 1u, &NumberOfBytesWritten, 0);
  FlushFileBuffers(v2);
  FileSize.QuadPart = 0i64;
  GetFileSizeEx(v2, &FileSize);
  SetFilePointer(v2, 0, 0, 0);
  v4 = FileSize.HighPart;
  v5 = FileSize.LowPart;
  v6 = 0;
  v7 = 0;
  if ( FileSize.HighPart >= 0 && (FileSize.HighPart > 0 || FileSize.LowPart > 0) )
  {
    while ( 1 )
    {
      v8 = __OFSUB__(__PAIR__(v4, v5), __PAIR__(v7, v6));
      v11 = v5 - v6;
      v9 = (__PAIR__(v4, v5) - __PAIR__((unsigned int)v7, v6)) >> 32;
      v10 = v5 - v6;
      if ( v9 < 0 || (unsigned __int8)((v9 < 0) ^ v8) | (v9 == 0) && v11 <= 0x1000 )
      {
        v15 = v9;
      }
      else
      {
        v10 = 4096;
        v15 = 0;
      }
      if ( !WriteFile(v2, &Buffer, v10, &NumberOfBytesWritten, 0) || !NumberOfBytesWritten )
        break;
      v4 = FileSize.HighPart;
      v12 = NumberOfBytesWritten + v6;
      v7 = (__PAIR__(v7, NumberOfBytesWritten) + (unsigned __int64)v6) >> 32;
      v6 += NumberOfBytesWritten;
      if ( v7 < FileSize.HighPart )
      {
        v5 = FileSize.LowPart;
      }
      else
      {
        if ( v7 > FileSize.HighPart )
          break;
        v5 = FileSize.LowPart;
        if ( v12 >= FileSize.LowPart )
          break;
      }
    }
  }
  FlushFileBuffers(v2);
  CloseHandle(v2);
  return sub_401000(lpFileName, 0);
}

//----- (00401230) --------------------------------------------------------
HANDLE sub_401230()
{
  HANDLE result; // eax
  void *v1; // esi
  int v2; // eax
  CHAR String2; // [esp+Ch] [ebp-674h]
  char v4; // [esp+Dh] [ebp-673h]
  char v5; // [esp+Eh] [ebp-672h]
  char v6; // [esp+Fh] [ebp-671h]
  char v7; // [esp+10h] [ebp-670h]
  char v8; // [esp+11h] [ebp-66Fh]
  char v9; // [esp+12h] [ebp-66Eh]
  char v10; // [esp+13h] [ebp-66Dh]
  char v11; // [esp+14h] [ebp-66Ch]
  char v12; // [esp+15h] [ebp-66Bh]
  char v13; // [esp+16h] [ebp-66Ah]
  int v14; // [esp+17h] [ebp-669h]
  int v15; // [esp+1Bh] [ebp-665h]
  char v16; // [esp+1Fh] [ebp-661h]
  struct _PROCESS_INFORMATION ProcessInformation; // [esp+20h] [ebp-660h]
  DWORD NumberOfBytesWritten; // [esp+30h] [ebp-650h]
  struct _STARTUPINFOA StartupInfo; // [esp+34h] [ebp-64Ch]
  CHAR Buffer; // [esp+78h] [ebp-608h]
  char v21; // [esp+79h] [ebp-607h]
  __int16 v22; // [esp+179h] [ebp-507h]
  char v23; // [esp+17Bh] [ebp-505h]
  CHAR Filename; // [esp+17Ch] [ebp-504h]
  char v25; // [esp+17Dh] [ebp-503h]
  __int16 v26; // [esp+27Dh] [ebp-403h]
  char v27; // [esp+27Fh] [ebp-401h]
  char Dest; // [esp+280h] [ebp-400h]
  char v29; // [esp+281h] [ebp-3FFh]
  __int16 v30; // [esp+67Dh] [ebp-3h]
  char v31; // [esp+67Fh] [ebp-1h]

  Filename = 0;
  memset(&v25, 0, 0x100u);
  v26 = 0;
  v27 = 0;
  GetModuleFileNameA(0, &Filename, 0x103u);
  v14 = 0;
  v5 = 116;
  v15 = 0;
  v12 = 116;
  v16 = 0;
  Buffer = 0;
  Dest = 0;
  memset(&v21, 0, 0x100u);
  v22 = 0;
  v23 = 0;
  memset(&v29, 0, 0x3FCu);
  v30 = 0;
  String2 = 101;
  v4 = 118;
  v6 = 99;
  v7 = 104;
  v8 = 107;
  v9 = 46;
  v10 = 98;
  v11 = 97;
  v13 = 0;
  v31 = 0;
  GetTempPathA(0x104u, &Buffer);
  lstrcatA(&Buffer, &String2);
  result = CreateFileA(&Buffer, 0x40000000u, 2u, 0, 2u, 0x80u, 0);
  v1 = result;
  if ( result != (HANDLE)-1 )
  {
    sprintf(&Dest, Format, &Filename, &Filename);
    v2 = lstrlenA(&Dest);
    WriteFile(v1, &Dest, v2, &NumberOfBytesWritten, 0);
    CloseHandle(v1);
    StartupInfo.cb = 68;
    memset(&StartupInfo.lpReserved, 0, 0x40u);
    ProcessInformation.hThread = 0;
    ProcessInformation.dwProcessId = 0;
    ProcessInformation.dwThreadId = 0;
    ProcessInformation.hProcess = 0;
    StartupInfo.dwFlags = 1;
    StartupInfo.wShowWindow = 0;
    result = (HANDLE)CreateProcessA(0, &Buffer, 0, 0, 0, 0, 0, 0, &StartupInfo, &ProcessInformation);
  }
  return result;
}

//----- (004013E0) --------------------------------------------------------
int __cdecl sub_4013E0(int a1, int a2)
{
  signed int v2; // esi
  signed int v3; // edx

  if ( a1 == 2 )
  {
    v2 = 1;
    do
    {
      sub_4010F0(*(LPCSTR *)(a2 + 4));
      if ( GetFileAttributesA(*(LPCSTR *)(a2 + 4)) == -1 )
        break;
      Sleep(0x3E8u);
      v3 = v2++;
    }
    while ( v3 < 50 );
  }
  sub_401230();
  return 0;
}

//----- (00401440) --------------------------------------------------------
int __stdcall WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd)
{
  int v4; // ST04_4
  int *v5; // eax

  v4 = *(_DWORD *)_p___argv();
  v5 = (int *)_p___argc();
  return sub_4013E0(*v5, v4);
}
// 40205C: using guessed type int _p___argc(void);
// 402060: using guessed type int _p___argv(void);

//----- (004017B0) --------------------------------------------------------
int sub_4017B0()
{
  return 0;
}

// ALL OK, 6 function(s) have been successfully decompiled
